import { Theme } from "protomaps-themes-base";

const WHITE = "rgba(255, 255, 255, 1)";
const BLACK = "rgba(0, 0, 0, 1)";

export default <Theme>{
  background: WHITE,
  earth: WHITE,
  park_a: WHITE,
  park_b: WHITE,
  hospital: WHITE,
  industrial: WHITE,
  school: WHITE,
  wood_a: WHITE,
  wood_b: WHITE,
  pedestrian: WHITE,
  scrub_a: WHITE,
  scrub_b: WHITE,
  glacier: WHITE,
  sand: WHITE,
  beach: WHITE,
  aerodrome: WHITE,
  runway: BLACK,
  water: BLACK,
  zoo: WHITE,
  military: WHITE,

  tunnel_other_casing: WHITE,
  tunnel_minor_casing: WHITE,
  tunnel_link_casing: WHITE,
  tunnel_major_casing: WHITE,
  tunnel_highway_casing: WHITE,
  tunnel_other: BLACK,
  tunnel_minor: BLACK,
  tunnel_link: BLACK,
  tunnel_major: BLACK,
  tunnel_highway: BLACK,

  pier: WHITE,
  buildings: "rgba(218, 222, 217, 1)",

  minor_service_casing: WHITE,
  minor_casing: WHITE,
  link_casing: WHITE,
  major_casing_late: WHITE,
  highway_casing_late: WHITE,
  other: BLACK,
  minor_service: BLACK,
  minor_a: BLACK,
  minor_b: BLACK,
  link: BLACK,
  major_casing_early: WHITE,
  major: BLACK,
  highway_casing_early: WHITE,
  highway: BLACK,

  railway: BLACK,
  boundaries: BLACK,
  waterway_label: WHITE,

  bridges_other_casing: WHITE,
  bridges_minor_casing: WHITE,
  bridges_link_casing: WHITE,
  bridges_major_casing: WHITE,
  bridges_highway_casing: WHITE,
  bridges_other: BLACK,
  bridges_minor: BLACK,
  bridges_link: BLACK,
  bridges_major: BLACK,
  bridges_highway: BLACK,

  roads_label_minor:   BLACK,
  roads_label_minor_halo:  WHITE,
  roads_label_major: BLACK,
  roads_label_major_halo: WHITE,
  ocean_label: WHITE,
  peak_label: BLACK,
  subplace_label: BLACK,
  subplace_label_halo: WHITE,
  city_label: BLACK,
  city_label_halo: WHITE,
  state_label: BLACK,
  state_label_halo: WHITE,
  country_label: BLACK
};
